server:
  port: 10101
eureka:
  client:
    service-url:
        defaultZone: http://127.0.0.1:10100/eureka/
spring:
  application:
    name: config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
