spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wait2315
    url: jdbc:mysql://localhost:3306/wb20230503_db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
